name: "Syslog (Fork)"
version: "0.4.2"
slug: "syslog"
description: "Send your HAOS logs to a remote syslog server (Fork with fix for mib1185/ha-addon-syslog#39)"
url: "https://github.com/thomas-de-lange/ha-addon-syslog"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
startup: services
journald: true
options:
  syslog_host: syslog.local
  syslog_port: 514
  syslog_protocol: udp
  syslog_ssl: false
  syslog_ssl_verify: true
schema:
  syslog_host: str
  syslog_port: int
  syslog_protocol: list(udp|tcp)
  syslog_ssl: bool
  syslog_ssl_verify: bool
